export const LOAD_LIVE_MATCHES_SUCCESS = 'LOAD_LIVE_MATCHES_SUCCESS';
export const LOAD_LIVE_MATCHES_ERROR = 'LOAD_LIVE_MATCHES_ERROR';
export const LOAD_CACHED_LIVE_MATCHES = 'LOAD_CACHED_LIVE_MATCHES';